project:
  type: website          
  output-dir: _site      

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hand-on_Ex01/" 
          - text: "Hands-on Exercise 2"
            href: "Hand-on_Ex02/"
          - text: "Hands-on Exercise 3"
            href: "Hand-on_Ex03/"
          - text: "Hands-on Exercise 4"
            href: "Hand-on_Ex04/"
          - text: "Hands-on Exercise 5"
            href: "Hand-on_Ex05/"
          - text: "Hands-on Exercise 6"
            href: "Hand-on_Ex06/"
            
      - text: "In-Class Exercise"
        menu:
          - text: "In-Class Exercise 2"
            href: "In-class_Ex02/"
          - text: "In-Class Exercise 3"
            href: "In-class_Ex03/"
          - text: "In-Class Exercise 5"
            href: "In-class_Ex05/"
          - text: "In-Class Exercise 6"
            href: "In-class_Ex06/"
          - text: "In-Class Exercise 7"
            href: "In-class_Ex07/"
            
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex01/"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex02/"
          - text: "Take-home Exercise 3"
            href: "Take-home_Ex03/"
            
      - text: "Group Project"
        href: "Group_Project/"
        
    right:
      - href: index.qmd                
        text: Home
      - about.qmd                      

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css                    

editor: visual