project:
  type: website          
  output-dir: _site      

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Exercise 1"
            href: "Hand-on_Ex01/" 
          - text: "Exercise 2"
            href: "Hand-on_Ex02/"
    right:
      - href: index.qmd                
        text: Home
      - about.qmd                      

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css                    
editor: visual
